/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_test_JniTest */

#ifndef _Included_com_jni_test_JniTest
#define _Included_com_jni_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_test_JniTest
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_test_JniTest_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
